-- MySQL Script generated by MySQL Workbench
-- 03/01/17 22:15:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kasan
-- -----------------------------------------------------
-- Kasanスキーマ
DROP SCHEMA IF EXISTS `kasan` ;

-- -----------------------------------------------------
-- Schema kasan
--
-- Kasanスキーマ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kasan` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `kasan` ;

-- -----------------------------------------------------
-- Table `kasan`.`m_organizatoin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kasan`.`m_organizatoin` ;

CREATE TABLE IF NOT EXISTS `kasan`.`m_organizatoin` (
  `no` BIGINT NOT NULL COMMENT '番号',
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  PRIMARY KEY (`no`))
ENGINE = InnoDB
COMMENT = '組織マスタ';


-- -----------------------------------------------------
-- Table `kasan`.`m_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kasan`.`m_member` ;

CREATE TABLE IF NOT EXISTS `kasan`.`m_member` (
  `no` BIGINT NOT NULL COMMENT '番号',
  `name` VARCHAR(30) NOT NULL COMMENT '名称',
  `email` VARCHAR(255) NOT NULL COMMENT 'Eメール',
  `password` BLOB NULL COMMENT 'パスワード',
  PRIMARY KEY (`no`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '会員マスタ';


-- -----------------------------------------------------
-- Table `kasan`.`m_authentication_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kasan`.`m_authentication_token` ;

CREATE TABLE IF NOT EXISTS `kasan`.`m_authentication_token` (
  `member_no` BIGINT NOT NULL COMMENT '会員番号',
  `token` VARCHAR(255) NOT NULL COMMENT 'トークン',
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  PRIMARY KEY (`member_no`),
  CONSTRAINT `fk_m_authentication_token.member_no`
    FOREIGN KEY (`member_no`)
    REFERENCES `kasan`.`m_member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '認証トークン';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
